{
 "title": "Miner Stats",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "PAC Hash Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MinerMetrics",
     "select": [
      [
       { "params": [ "HashRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Miner", "operator": "=", "value": "PAC" }
     ]
    }
   ]
  },
  {
   "title": "BIG Hash Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MinerMetrics",
     "select": [
      [
       { "params": [ "HashRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Miner", "operator": "=", "value": "BIG" }
     ]
    }
   ]
  },
  {
   "title": "JID Hash Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MinerMetrics",
     "select": [
      [
       { "params": [ "HashRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Miner", "operator": "=", "value": "JID" }
     ]
    }
   ]
  },
  {
   "title": "Farm Hash Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PoolMetrics",
     "select": [
      [
       { "params": [ "MinerHashRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PAC Algo",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "MinerMetrics",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Miner", "operator": "=", "value": "PAC" }
     ]
    }
   ]
  },
  {
   "title": "BIG Algo",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "MinerMetrics",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Miner", "operator": "=", "value": "BIG" }
     ]
    }
   ]
  },
  {
   "title": "JID Algo",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "MinerMetrics",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Miner", "operator": "=", "value": "JID" }
     ]
    }
   ]
  },
  {
   "title": "Proxy Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ProxyMetrics",
     "select": [
      [
       { "params": [ "UpTime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PAC Temp",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "coretemp_cpu",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "PAC" }
     ]
    }
   ]
  },
  {
   "title": "BIG Temp",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "coretemp_cpu",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "BIG" }
     ]
    }
   ]
  },
  {
   "title": "JID Temp",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "coretemp_cpu",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "JID" }
     ]
    }
   ]
  },
  {
   "title": "Proxy Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ProxyMetrics",
     "select": [
      [
       { "params": [ "Latency" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PAC Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MinerMetrics",
     "select": [
      [
       { "params": [ "UpTime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Miner", "operator": "=", "value": "PAC" }
     ]
    }
   ]
  },
  {
   "title": "BIG Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MinerMetrics",
     "select": [
      [
       { "params": [ "UpTime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Miner", "operator": "=", "value": "BIG" }
     ]
    }
   ]
  },
  {
   "title": "JID Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MinerMetrics",
     "select": [
      [
       { "params": [ "UpTime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Miner", "operator": "=", "value": "JID" }
     ]
    }
   ]
  },
  {
   "title": "Farm Power",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PowerDraw",
     "select": [
      [
       { "params": [ "FarmPowerDraw" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PAC Power",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PowerDraw",
     "select": [
      [
       { "params": [ "PACPowerDraw" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "BIG Power",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PowerDraw",
     "select": [
      [
       { "params": [ "BIGPowerDraw" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "JID Power",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PowerDraw",
     "select": [
      [
       { "params": [ "JIDPowerDraw" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Historical",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "PAC Hash Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "Hs" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "MinerMetrics",
       "select": [
        [
         { "params": [ "HashRate" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Miner", "operator": "=", "value": "PAC" }
       ]
      }
     ]
    },
    {
     "title": "BIG Hash Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "Hs" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "MinerMetrics",
       "select": [
        [
         { "params": [ "HashRate" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Miner", "operator": "=", "value": "BIG" }
       ]
      }
     ]
    },
    {
     "title": "JID Hash Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "Hs" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "MinerMetrics",
       "select": [
        [
         { "params": [ "HashRate" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "Miner", "operator": "=", "value": "JID" }
       ]
      }
     ]
    },
    {
     "title": "PAC Temp",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "coretemp_cpu",
       "select": [
        [
         { "params": [ "temperature" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "PAC" }
       ]
      }
     ]
    },
    {
     "title": "BIG Temp",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "coretemp_cpu",
       "select": [
        [
         { "params": [ "temperature" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "BIG" }
       ]
      }
     ]
    },
    {
     "title": "JID Temp",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "coretemp_cpu",
       "select": [
        [
         { "params": [ "temperature" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "JID" }
       ]
      }
     ]
    },
    {
     "title": "PAC Power",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "mwatt" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "PowerDraw",
       "select": [
        [
         { "params": [ "PACPowerDraw" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "BIG Power",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "mwatt" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "PowerDraw",
       "select": [
        [
         { "params": [ "BIGPowerDraw" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "JID Power",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "mwatt" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "PowerDraw",
       "select": [
        [
         { "params": [ "JIDPowerDraw" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Proxy Latency",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ProxyMetrics",
       "select": [
        [
         { "params": [ "Latency" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}